### ISSUE TITLE
New updates for study 1

### ISSUE THREAD

**Issue by thuanGIT** [thuanGIT/face_detection_demo#1]
## Tasks

- [ ] External app for showing what to select next
- [ ] Add sound/vibration to indicate boundary (edited) 
- [ ] After a trial, phone should be moved back to the middle
- [ ] increase counter when a participant hits submit button
- [ ] Make the submit button large (i.e., same as the settings page)
